[build]
  publish = "."  # or the folder with index.html

[dev]
  command = "npx serve"  # serves static files
  targetPort = 3000       # npx serve uses port 3000 by default
  port = 8888             # Netlify's proxy port
  functions = "netlify/functions"
